### PR TITLE
Multi page form - With suggested changes

### PR DESCRIPTION
**Pull request by kaakshay**
@pkarman : I have made the changes as you suggested. Kindly have a look and let me know if it's fine.

### CODE REVIEW

**Comment by kaakshay** [comment]
@pkarman : I have added the script inline. Please have a look and let me know.

**Comment by pkarman** [comment]
I must not have communicated this correctly, I'm sorry.

I didn't mean that the `mpform.js` contents should be dynamically inlined into the HTML page at run time. I meant that the contents of the `mpform.js` file should be refactored as methods within the `pinform.js` file.

There's other clean up to be done, so don't bother changing it at this point. I can take it from here.

**Comment by harisubramaniam** [comment]
@pkarman So can I take it that you will make the other changes and test the form?

**Comment by pkarman** [comment]
@harisubramaniam yes, I will take it from here.

**Pull request closed without merging**
